version: '3'
services:
    api-server: 
        image: api-server
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        # container_name: simple-blogging-website
        depends_on:
            - mongo_db

    mongo_db:
        image: mongo
        ports:
            - "27017:27017"
        # container_name: simple-blogging-website
        volumes:
            - ./db/://c/Program Files/MongoDB/Server/4.4/data/simple-blogging-website-backend